main: tk.kaylandfly.KayLandFlyPlugin
name: KayLandFly
version: 1.0
commands:
  kaylandfly:
    aliases:
    - klf
    description: Manager plugin
    permission: kaylandfly.admin
  kaylandflyfly:
    aliases:
    - klffly
    - fly
    description: Enable/Disable fly mode!
    permission: kaylandfly.use
  kaylandflyflybuy:
    aliases:
    - klfflybuy
    - flybuy
    description: Can buy seconds
    permission: kaylandfly.flybuy
permissions:
  kaylandfly.admin:
    description: Can use kaylandfly command
  kaylandfly.use:
    description: Can use fly command
  kaylandfly.use.other:
    description: Can active fly other player
  kaylandfly.use.unlimited:
    description: Can use fly mode unlimited
    
  